name: Add Sentence
description: Add a sample sentence in Ladino and in at least on other language.
title: "Fraza mueva"
labels: ["example"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: ladino
    attributes:
      label: Ladino
      description: Una fraza en ladino.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - inglez
        - ebreo
        - fransez
        - portugez
        - turko
        - kasteyano
      multiple: false
      default: 0
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Teksto en la otra lingua
      description: Por favor eskrive aki la traduksion de la fraza en la otra lingua.
      render: shell

